[custom]
;https://subapi.v1.mk/remoteconfig/2024/03/0308/9d1669d3b77703b6b373f1cd10b126e3.ini
;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

;设置规则标志位
ruleset=🚀 节点选择,https://raw.githubusercontent.com/MaxwellChang98/shadowrocket-role/refs/heads/main/clash/proxy.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/MaxwellChang98/shadowrocket-role/refs/heads/main/clash/direct.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/Loyalsoldier/clash-rules/refs/heads/release/proxy.txt
ruleset=🚀 节点选择,https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/refs/heads/release/proxy-list.txt
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=Ⓜ️ 微软云盘,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=📲 Telegram,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=📹 YouTube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🌏 国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
; ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/ProxyMedia.list
;ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,[]GEOIP,CN
;ruleset=🇺🇲 美国IP,[]GEOIP,US
ruleset=🇪🇺 欧洲IP,https://raw.githubusercontent.com/MaxwellChang98/shadowrocket-role/refs/heads/main/clash/EuIp.list
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]🔯 故障转移`[]🔮 负载均衡`[]🚀 手动切换`[]DIRECT`[]🇭🇰 香港节点-自动`[]🇹🇼 台湾节点-自动`[]🇯🇵 日本节点-自动`[]🇺🇲 美国节点-自动`[]🇺🇲 美国1.0-自动`[]🇺🇲 美国1.5-自动`[]🇪🇺 欧洲节点-自动`[]🇦🇺 澳大利亚-自动`[]🇸🇬 新加坡-自动
custom_proxy_group=🚀 手动切换`select`.*
custom_proxy_group=♻️ 自动选择`url-test`(^(?!.*x(?:[2-9]|[1-9][0-9])))`https://www.google.com/generate_204`60,5,50
custom_proxy_group=🔮 负载均衡`load-balance`.*`https://www.google.com/generate_204`10,5,200
custom_proxy_group=🔯 故障转移`fallback`(?i)^(?!.*(香港|hong[ -]?kong|\bHK\b)).*$`https://www.google.com/generate_204`60,5,50
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]♻️ 自动选择`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📲 Telegram`select`[]🚀 节点选择`[]♻️ 自动选择`[]🚀 手动切换
custom_proxy_group=📹 YouTube`select`[]🚀 节点选择`[]♻️ 自动选择`[]🚀 手动切换


custom_proxy_group=🇭🇰 香港节点-自动`url-test`(^(?!.*x(?:[2-9]|[1-9][0-9]))(?=.*(?:港|香港|HongKong|HK|Hong Kong)).*$)`https://www.google.com/generate_204`60,5,50
custom_proxy_group=🇯🇵 日本节点-自动`url-test`(^(?!.*x(?:[2-9]|[1-9][0-9]))(?=.*(?:日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)).*$)`https://www.google.com/generate_204`60,5,50
custom_proxy_group=🇺🇲 美国节点-自动`url-test`(^(?!.*x(?:[2-9]|[1-9][0-9]))(?=.*(?:美|美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|United States|(?<![a-zA-Z])US(?![a-zA-Z])|(?<![a-zA-Z])USA(?![a-zA-Z])|(?<![a-zA-Z])USD(?![a-zA-Z]))).*$)`https://www.google.com/generate_204`60,5,150
custom_proxy_group=🇺🇲 美国1.0-自动`url-test`(^(?!.*x(?:[2-9]|[1-9][0-9]))(?=.*(?:美|美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|United States|(?<![a-zA-Z])US(?![a-zA-Z])|(?<![a-zA-Z])USA(?![a-zA-Z])|(?<![a-zA-Z])USD(?![a-zA-Z]))(?=.*1\.0)).*$)`https://www.google.com/generate_204`60,5,150
custom_proxy_group=🇺🇲 美国1.5-自动`url-test`(^(?!.*x(?:[2-9]|[1-9][0-9]))(?=.*(?:美|美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|United States|(?<![a-zA-Z])US(?![a-zA-Z])|(?<![a-zA-Z])USA(?![a-zA-Z])|(?<![a-zA-Z])USD(?![a-zA-Z]))(?=.*1\.5)).*$)`https://www.google.com/generate_204`60,5,150
custom_proxy_group=🇹🇼 台湾节点-自动`url-test`(^(?!.*x(?:[2-9]|[1-9][0-9]))(?=.*(?:台|新北|彰化|TW|Taiwan)).*$)`https://www.google.com/generate_204`60,5,50
custom_proxy_group=🇪🇺 欧洲节点-自动`url-test`(^(?!.*x(?:[2-9]|[1-9][0-9]))(?=.*(?:UK|英|伦敦|DE|德|NL|荷兰|爱沙尼亚|Estonia|EE)).*$)`https://www.google.com/generate_204`60,5,50
#custom_proxy_group=🇩🇪 德国节点-自动`url-test`(^(?!.*x(?:[2-9]|[1-9][0-9]))(?=.*(?:DE|德)).*$)`https://www.google.com/generate_204`60,5,50
#custom_proxy_group=🇳🇱 荷兰节点-自动`url-test`(^(?!.*x(?:[2-9]|[1-9][0-9]))(?=.*(?:NL|荷兰)).*$)`https://www.google.com/generate_204`60,5,50
custom_proxy_group=🇦🇺 澳大利亚-自动`url-test`(^(?!.*x(?:[2-9]|[1-9][0-9]))(?=.*(?:土澳|澳大利亚|澳|AUS)).*$)`https://www.google.com/generate_204`60,5,50
#custom_proxy_group=🇪🇪 爱沙尼亚-自动`url-test`(^(?!.*x(?:[2-9]|[1-9][0-9]))(?=.*(?:爱沙尼亚|Estonia|EE)).*$)`https://www.google.com/generate_204`60,5,50
custom_proxy_group=🇸🇬 新加坡-自动`url-test`(^(?!.*x(?:[2-9]|[1-9][0-9]))(?=.*(?:新加坡|SG)).*$)`https://www.google.com/generate_204`60,5,50


custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]♻️ 自动选择`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🌏 国内媒体`select`[]DIRECT`[]🇭🇰 香港节点-自动`[]🇹🇼 台湾节点-自动`[]🇯🇵 日本节点-自动`[]🇺🇲 美国节点-自动`[]🇺🇲 美国1.0-自动`[]🇺🇲 美国1.5-自动`[]🇦🇺 澳大利亚-自动`[]🇸🇬 新加坡-自动`[]🚀 手动切换
custom_proxy_group=📢 谷歌FCM`select`[]🚀 节点选择`[]♻️ 自动选择`[]🚀 手动切换`[]🇭🇰 香港节点-自动`[]🇹🇼 台湾节点-自动`[]🇯🇵 日本节点-自动`[]🇺🇲 美国节点-自动`[]🇺🇲 美国1.0-自动`[]🇺🇲 美国1.5-自动`[]🇦🇺 澳大利亚-自动`[]🇸🇬 新加坡-自动
custom_proxy_group=Ⓜ️ 微软云盘`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点-自动`[]🇹🇼 台湾节点-自动`[]🇯🇵 日本节点-自动`[]🇺🇲 美国节点-自动`[]🇺🇲 美国1.0-自动`[]🇺🇲 美国1.5-自动`[]🇦🇺 澳大利亚-自动`[]🇸🇬 新加坡-自动`[]🚀 手动切换
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点-自动`[]🇹🇼 台湾节点-自动`[]🇯🇵 日本节点-自动`[]🇺🇲 美国节点-自动`[]🇺🇲 美国1.0-自动`[]🇺🇲 美国1.5-自动`[]🇦🇺 澳大利亚-自动`[]🇸🇬 新加坡-自动`[]🚀 手动切换
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🆎 AdBlock`select`[]REJECT`[]DIRECT
custom_proxy_group=🛡️ 隐私防护`select`[]REJECT`[]DIRECT
;custom_proxy_group=🇺🇲 美国IP`select`[]🇺🇲 美国节点-自动`[]🚀 节点选择`[]DIRECT
custom_proxy_group=🇪🇺 欧洲IP`select`[]🇪🇺 欧洲节点-自动`[]🚀 节点选择`[]DIRECT
;设置分组标志位


emoji=中国,🇨🇳
emoji=香港,🇭🇰
emoji=澳门,🇲🇴
emoji=台湾,🇹🇼
emoji=日本,🇯🇵
emoji=韩国,🇰🇷
emoji=新加坡,🇸🇬
emoji=马来西亚,🇲🇾
emoji=泰国,🇹🇭
emoji=越南,🇻🇳
emoji=印度,🇮🇳
emoji=印度尼西亚,🇮🇩
emoji=菲律宾,🇵🇭
emoji=沙特阿拉伯,🇸🇦
emoji=阿联酋,🇦🇪
emoji=土耳其,🇹🇷
emoji=以色列,🇮🇱
emoji=巴基斯坦,🇵🇰
emoji=哈萨克斯坦,🇰🇿

emoji=俄罗斯,🇷🇺
emoji=英国,🇬🇧
emoji=法国,🇫🇷
emoji=德国,🇩🇪
emoji=意大利,🇮🇹
emoji=西班牙,🇪🇸
emoji=荷兰,🇳🇱
emoji=瑞士,🇨🇭
emoji=瑞典,🇸🇪
emoji=挪威,🇳🇴
emoji=波兰,🇵🇱
emoji=乌克兰,🇺🇦
emoji=希腊,🇬🇷
emoji=葡萄牙,🇵🇹
emoji=比利时,🇧🇪
emoji=奥地利,🇦🇹
emoji=爱尔兰,🇮🇪
emoji=爱沙尼亚,🇪🇪

emoji=美国,🇺🇸
emoji=加拿大,🇨🇦
emoji=墨西哥,🇲🇽
emoji=巴西,🇧🇷
emoji=阿根廷,🇦🇷
emoji=哥伦比亚,🇨🇴
emoji=智利,🇨🇱
emoji=秘鲁,🇵🇪
emoji=古巴,🇨🇺

emoji=澳大利亚,🇦🇺
emoji=新西兰,🇳🇿
emoji=斐济,🇫🇯
emoji=巴布亚新几内亚,🇵🇬

emoji=埃及,🇪🇬
emoji=南非,🇿🇦
emoji=尼日利亚,🇳🇬
emoji=肯尼亚,🇰🇪
emoji=摩洛哥,🇲🇦
emoji=埃塞俄比亚,🇪🇹
emoji=阿尔及利亚,🇩🇿

enable_rule_generator=true
overwrite_original_rules=true
skip_failed_links=true

max_concurrent_threads=50
[node_pref]
#过滤节点，正则匹配
rename_node=中国@

sort_script=function compare(node_a, node_b) {\n    return node_a.Remark > node_b.Remark;\n}
;luck
